pool: WindowsPool

stages:
  - stage: Deploy
    jobs:
      - job: DeployJob
        steps:
          - task: ServiceNow-CICD-App-Install@2
            name: CICDInstall
            inputs:
              connectedServiceName: snow_CICD
              scope: global
              sysId: 97ac9b1047641210acd2a22f316d432f
              autoUpgradeBaseApp: true

